services:
  postgres:
    image: postgres:15-alpine
    environment:
      - user=airflow
      - pass=airflow
      - db=airflow
    ports:
      - "5432.5432"

  airflow-engine:
    image: apache/airflow:2.7.1-python3.11
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    ports:
      - "8080.8080"

    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/plugins/src
      - ./data:/opt/airflow/data

    command: bash -c "airflow db init && airflow users create --username admin --password admin --firstname DataOps --lastname Alpha --role Admin --email admin@local.com && airflow webserver & airflow scheduler"